import { chromium } from 'playwright-core';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const __dirname = dirname(fileURLToPath(import.meta.url));
const browser = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const page = await browser.newPage();
const fails=[];
page.on('requestfailed', r => fails.push(r.url()+' :: '+r.failure()?.errorText));
page.on('response', r => { if(r.url().includes('font')) console.log('RESP', r.status(), r.url()); });
await page.goto('file://'+join(__dirname,'hero-clean.html'), { waitUntil:'networkidle' }).catch(e=>console.log('goto err',e.message));
await page.waitForTimeout(2000);
const loaded = await page.evaluate(() => Array.from(document.fonts).map(f=>f.family+' '+f.weight+' '+f.status));
console.log('FONTS:', loaded);
console.log('FAILS:', fails);
await browser.close();
